version: '2'

services:

  mysql:
    image: mysql:5.7.19
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"

  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/containers/data/redis:/data

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  #   container_name: elasticsearch
  #   volumes:
  #     - /var/lib/containers/data/es:/usr/share/elasticsearch/data
  #   environment:
  #     - http.host=0.0.0.0
  #     - transport.host=127.0.0.1
  #     - cluster.name=es-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - xpack.security.enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.5.1
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200